### ISSUE TITLE
why use relative and top attributes

### ISSUE THREAD

**Issue by fusco** [david-becu/projetfallout#1]
https://github.com/david-becu/projetfallout/blob/fea5d212b0c68ec14fdd0a3da36a82455bccb70d/style.css#L58

```css
footer > p {
  position: relative;
  color: white;
  text-align: center;
  top: 150px;

 }

```
