### ISSUE TITLE
white space and indentation

### ISSUE THREAD

**Issue by fusco** [david-becu/projetfallout#5]
```css

  .positionable {
    left: 475px;
    
        
  }
  
    .societe {
      position: relative;
      transform: rotate(1.75turn);
      background-color: orange;
      margin: 10px;
      padding: 10px;
      width: 140px;
      top: 5px;
    }
```
